# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2608a6ede56a51c5aa4dbf0b2dee28aa316fd6372546b0c7e567f9cfad8a4c26245f734140663921bb6c2a0fa419c4b1268ed616a3a21502f478e4348fc6d1

test:
  secret_key_base: 3d738b89430b1ab8ad32ac6f7648362cddc99bdea099bbf70c6a4849ad9a158208440aa52c1a501cc5ae8ce5dfd7869eb01b920d75528d722c8f2dc53e0464b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
